[workspace]
resolver = "3"
members = [
  "voxalfa-validator",
  "voxalfa-formatter",
  "voxalfa-midi",
  "voxalfa-cli",
  "tree-sitter-voxalfa",
]

[workspace.dependencies]
thiserror = "2.0.18"
tree-sitter-voxalfa = { path = "./tree-sitter-voxalfa" }
voxalfa-midi = { path = "./voxalfa-midi" }
voxalfa-formatter = { path = "./voxalfa-formatter" }
voxalfa-validator = { path = "./voxalfa-validator" }
