[workspace]
resolver = "3"
members = [
  "voxalfa-cli",
  "voxalfa-core",
  "voxalfa-lsp",
  "voxalfa-midi",
  "voxalfa-formatter",
  "voxalfa-svg",
  "tree-sitter-voxalfa",
]

[workspace.dependencies]
insta = "1.48.0"
thiserror = "2.0.18"
tree-sitter-voxalfa = { path = "./tree-sitter-voxalfa" }
voxalfa-midi = { path = "./voxalfa-midi" }
voxalfa-formatter = { path = "./voxalfa-formatter" }
voxalfa-core = { path = "./voxalfa-core" }
