[package]
name = "voxalfa-lsp"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "src/main.rs"
name = "voxalfa-ls"

[dependencies]
async-lsp = { version = "0.2.4", features = ["tokio"] }
futures = "0.3.33"
ropey = "1.6.1"
tokio = { version = "1.53.1", features = ["macros", "rt", "io-std"] }
tokio-util = { version = "0.7.19", features = ["compat","futures-io"] }
tower = "0.5.3"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
voxalfa-core = { workspace = true }
voxalfa-formatter = { workspace = true }
tree-sitter = "0.26.11"
